import { AcquisitionTask } from '@/types/Acquisition';
import { subDays, addDays } from 'date-fns';

export const mockAcquisitionTasks: AcquisitionTask[] = [
  {
    id: '1',
    title: 'Campanha Google Ads Q4',
    description: 'Campanha de performance no Google Ads focada em conversão',
    channel: 'paid-search',
    status: 'active',
    priority: 'high',
    startDate: subDays(new Date(), 15).toISOString(),
    endDate: addDays(new Date(), 45).toISOString(),
    createdAt: subDays(new Date(), 20).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 50000,
      spent: 32500,
      impressions: 125000,
      clicks: 3750,
      leads: 187,
      conversions: 45,
      cpl: 173.80,
      cpc: 8.67,
      ctr: 3.0,
      conversionRate: 1.2,
    },
    goals: {
      targetLeads: 300,
      targetBudget: 50000,
      targetCPL: 166.67,
      targetConversionRate: 1.5,
    },
    tags: ['Google Ads', 'Performance', 'B2B'],
    assignedTo: 'Marketing Team',
    notes: [
      'CTR acima da média do setor (2.5%)',
      'Testar novos ad copies esta semana',
    ],
    checklist: [
      { id: 'c1', text: 'Criar grupos de anúncios por persona', done: true },
      { id: 'c2', text: 'Configurar tracking de conversão', done: true },
      { id: 'c3', text: 'Otimizar lances automáticos', done: true },
      { id: 'c4', text: 'Revisar negative keywords', done: false },
      { id: 'c5', text: 'Criar relatório semanal', done: false },
    ],
  },
  {
    id: '2',
    title: 'SEO - Conteúdo para Blog',
    description: 'Produção de 20 artigos otimizados para SEO',
    channel: 'organic-search',
    status: 'in-progress',
    priority: 'high',
    startDate: subDays(new Date(), 30).toISOString(),
    endDate: addDays(new Date(), 30).toISOString(),
    createdAt: subDays(new Date(), 35).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    metrics: {
      budget: 20000,
      spent: 12000,
      impressions: 85000,
      clicks: 4250,
      leads: 127,
      conversions: 38,
      cpl: 94.49,
      cpc: 2.82,
      ctr: 5.0,
      conversionRate: 0.89,
    },
    goals: {
      targetLeads: 200,
      targetBudget: 20000,
      targetCPL: 100.00,
      targetConversionRate: 1.0,
    },
    tags: ['SEO', 'Content', 'Organic'],
    assignedTo: 'Content Team',
    notes: [
      '12 artigos publicados, 8 em produção',
      'Ranking melhorando para keywords principais',
    ],
    checklist: [
      { id: 'c1', text: 'Pesquisa de palavras-chave', done: true },
      { id: 'c2', text: 'Criar calendário editorial', done: true },
      { id: 'c3', text: 'Escrever 20 artigos', done: false },
      { id: 'c4', text: 'Otimizar meta tags', done: false },
      { id: 'c5', text: 'Link building interno', done: false },
    ],
  },
  {
    id: '3',
    title: 'LinkedIn Ads - Geração de Leads B2B',
    description: 'Campanhas patrocinadas no LinkedIn para decisores',
    channel: 'social-paid',
    status: 'active',
    priority: 'high',
    startDate: subDays(new Date(), 20).toISOString(),
    endDate: addDays(new Date(), 40).toISOString(),
    createdAt: subDays(new Date(), 25).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 35000,
      spent: 22400,
      impressions: 180000,
      clicks: 5400,
      leads: 216,
      conversions: 54,
      cpl: 103.70,
      cpc: 4.15,
      ctr: 3.0,
      conversionRate: 1.0,
    },
    goals: {
      targetLeads: 300,
      targetBudget: 35000,
      targetCPL: 116.67,
      targetConversionRate: 1.2,
    },
    tags: ['LinkedIn', 'B2B', 'Social Media'],
    assignedTo: 'Social Team',
    notes: [
      'Audiências de cargos executivos performando bem',
      'Testar novos criativos semana que vem',
    ],
    checklist: [
      { id: 'c1', text: 'Definir públicos-alvo', done: true },
      { id: 'c2', text: 'Criar variações de anúncios', done: true },
      { id: 'c3', text: 'Configurar lead gen forms', done: true },
      { id: 'c4', text: 'Otimizar por cargo', done: false },
      { id: 'c5', text: 'A/B test de criativos', done: false },
    ],
  },
  {
    id: '4',
    title: 'Email Nurturing - Trial Users',
    description: 'Sequência de emails para converter usuários trial',
    channel: 'email',
    status: 'active',
    priority: 'medium',
    startDate: subDays(new Date(), 60).toISOString(),
    endDate: addDays(new Date(), 90).toISOString(),
    createdAt: subDays(new Date(), 65).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 8000,
      spent: 3200,
      impressions: 0, // Email não tem impressions
      clicks: 1280,
      leads: 0, // Já são leads
      conversions: 64,
      cpl: 0,
      cpc: 2.50,
      ctr: 0, // Taxa de abertura seria diferente
      conversionRate: 5.0,
    },
    goals: {
      targetLeads: 0,
      targetBudget: 8000,
      targetCPL: 0,
      targetConversionRate: 6.0,
    },
    tags: ['Email', 'Nurturing', 'Conversion'],
    assignedTo: 'Email Team',
    notes: [
      'Open rate: 35% (acima da média)',
      'Email 3 da sequência com melhor CTR',
    ],
    checklist: [
      { id: 'c1', text: 'Criar sequência de 7 emails', done: true },
      { id: 'c2', text: 'Segmentar por comportamento', done: true },
      { id: 'c3', text: 'Configurar automação', done: true },
      { id: 'c4', text: 'A/B test subject lines', done: false },
      { id: 'c5', text: 'Otimizar timing de envio', done: false },
    ],
  },
  {
    id: '5',
    title: 'Instagram & Facebook Ads',
    description: 'Campanhas de awareness e consideração',
    channel: 'social-paid',
    status: 'in-progress',
    priority: 'medium',
    startDate: subDays(new Date(), 10).toISOString(),
    endDate: addDays(new Date(), 50).toISOString(),
    createdAt: subDays(new Date(), 15).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 25000,
      spent: 8500,
      impressions: 450000,
      clicks: 13500,
      leads: 270,
      conversions: 54,
      cpl: 31.48,
      cpc: 0.63,
      ctr: 3.0,
      conversionRate: 0.4,
    },
    goals: {
      targetLeads: 500,
      targetBudget: 25000,
      targetCPL: 50.00,
      targetConversionRate: 0.5,
    },
    tags: ['Facebook', 'Instagram', 'Awareness'],
    assignedTo: 'Social Team',
    notes: [
      'Stories performando melhor que feed',
      'Audiência lookalike trazendo leads qualificados',
    ],
    checklist: [
      { id: 'c1', text: 'Criar criativos para Stories', done: true },
      { id: 'c2', text: 'Configurar pixel de conversão', done: true },
      { id: 'c3', text: 'Testar diferentes CTAs', done: false },
      { id: 'c4', text: 'Criar audiência lookalike', done: true },
      { id: 'c5', text: 'Otimizar por placement', done: false },
    ],
  },
  {
    id: '6',
    title: 'Programa de Parcerias',
    description: 'Co-marketing com parceiros estratégicos',
    channel: 'partnerships',
    status: 'planning',
    priority: 'medium',
    startDate: addDays(new Date(), 7).toISOString(),
    endDate: addDays(new Date(), 90).toISOString(),
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 30000,
      spent: 0,
      impressions: 0,
      clicks: 0,
      leads: 0,
      conversions: 0,
      cpl: 0,
      cpc: 0,
      ctr: 0,
      conversionRate: 0,
    },
    goals: {
      targetLeads: 200,
      targetBudget: 30000,
      targetCPL: 150.00,
      targetConversionRate: 2.0,
    },
    tags: ['Partnerships', 'Co-marketing', 'B2B'],
    assignedTo: 'Partnerships Team',
    notes: [
      'Negociando com 3 parceiros potenciais',
      'Foco em webinars e conteúdo co-branded',
    ],
    checklist: [
      { id: 'c1', text: 'Identificar parceiros estratégicos', done: true },
      { id: 'c2', text: 'Propor termos de co-marketing', done: false },
      { id: 'c3', text: 'Criar materiais compartilhados', done: false },
      { id: 'c4', text: 'Planejar webinar conjunto', done: false },
      { id: 'c5', text: 'Definir tracking de leads', done: false },
    ],
  },
  {
    id: '7',
    title: 'Webinar Series - Thought Leadership',
    description: 'Série mensal de webinars educacionais',
    channel: 'content',
    status: 'active',
    priority: 'high',
    startDate: subDays(new Date(), 40).toISOString(),
    endDate: addDays(new Date(), 80).toISOString(),
    createdAt: subDays(new Date(), 45).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 15000,
      spent: 7500,
      impressions: 75000,
      clicks: 3000,
      leads: 450,
      conversions: 90,
      cpl: 16.67,
      cpc: 2.50,
      ctr: 4.0,
      conversionRate: 3.0,
    },
    goals: {
      targetLeads: 600,
      targetBudget: 15000,
      targetCPL: 25.00,
      targetConversionRate: 3.5,
    },
    tags: ['Webinar', 'Content', 'Education'],
    assignedTo: 'Content Team',
    notes: [
      '3 webinars realizados, 450 inscritos',
      'Taxa de comparecimento: 60%',
    ],
    checklist: [
      { id: 'c1', text: 'Definir temas dos webinars', done: true },
      { id: 'c2', text: 'Convidar speakers externos', done: true },
      { id: 'c3', text: 'Criar landing pages', done: true },
      { id: 'c4', text: 'Promover nas redes sociais', done: true },
      { id: 'c5', text: 'Follow-up pós-webinar', done: false },
    ],
  },
  {
    id: '8',
    title: 'Programa de Indicação',
    description: 'Sistema de referral para clientes atuais',
    channel: 'referral',
    status: 'planning',
    priority: 'low',
    startDate: addDays(new Date(), 14).toISOString(),
    endDate: addDays(new Date(), 120).toISOString(),
    createdAt: subDays(new Date(), 3).toISOString(),
    updatedAt: new Date().toISOString(),
    metrics: {
      budget: 10000,
      spent: 0,
      impressions: 0,
      clicks: 0,
      leads: 0,
      conversions: 0,
      cpl: 0,
      cpc: 0,
      ctr: 0,
      conversionRate: 0,
    },
    goals: {
      targetLeads: 150,
      targetBudget: 10000,
      targetCPL: 66.67,
      targetConversionRate: 5.0,
    },
    tags: ['Referral', 'Customer Success', 'Growth'],
    assignedTo: 'Growth Team',
    notes: [
      'Definindo estrutura de incentivos',
      'Integração com CRM planejada',
    ],
    checklist: [
      { id: 'c1', text: 'Definir recompensas', done: true },
      { id: 'c2', text: 'Criar sistema de tracking', done: false },
      { id: 'c3', text: 'Desenvolver landing page', done: false },
      { id: 'c4', text: 'Comunicar aos clientes', done: false },
      { id: 'c5', text: 'Treinar CS team', done: false },
    ],
  },
];

export const availableAcquisitionTags = [
  'Google Ads',
  'Facebook',
  'Instagram',
  'LinkedIn',
  'SEO',
  'Content',
  'Email',
  'Webinar',
  'Partnerships',
  'Referral',
  'B2B',
  'B2C',
  'Performance',
  'Awareness',
  'Consideration',
  'Conversion',
  'Nurturing',
  'Growth',
  'Organic',
  'Paid',
];
