import { LandingPageTemplate } from '@/types/LandingPage';

// Templates tecnológicos premium com design elevado
export const PREMIUM_TEMPLATES: LandingPageTemplate[] = [
  {
    id: 'saas-platform',
    name: 'SaaS Platform',
    category: 'saas',
    description: 'Plataforma SaaS moderna com design cyberpunk',
    thumbnail: '/templates/saas-platform.png',
    palette: 'cyberpunk',
    typography: 'tech',
    components: [
      {
        id: '1',
        type: 'hero-fullscreen',
        props: {
          title: 'A Próxima Geração de Produtividade',
          subtitle: 'Novidade 2025',
          description: 'Transforme seu workflow com inteligência artificial e automação avançada',
          primaryCTA: 'Começar Gratuitamente',
          secondaryCTA: 'Ver Demo',
          palette: 'cyberpunk',
          typography: 'tech',
          alignment: 'center',
          overlay: true,
          overlayOpacity: 70,
        },
        styles: {},
      },
      {
        id: '2',
        type: 'bento-grid',
        props: {
          items: [
            {
              title: 'IA Integrada',
              description: 'Assistente inteligente que aprende com você',
              icon: 'zap',
              size: 'large',
              highlight: true,
            },
            {
              title: 'Segurança Enterprise',
              description: 'Certificações SOC 2 e ISO 27001',
              icon: 'shield',
              size: 'medium',
            },
            {
              title: 'Analytics Avançado',
              description: 'Insights em tempo real',
              icon: 'trending',
              size: 'medium',
            },
            {
              title: 'Integrações',
              description: '500+ apps conectados',
              icon: 'check',
              size: 'small',
            },
            {
              title: 'Performance',
              description: '99.99% uptime garantido',
              icon: 'award',
              size: 'small',
            },
            {
              title: 'Suporte 24/7',
              description: 'Time sempre disponível',
              icon: 'star',
              size: 'medium',
            },
          ],
          palette: 'cyberpunk',
          style: 'glassmorphism',
        },
        styles: {},
      },
      {
        id: '3',
        type: 'interactive-showcase',
        props: {
          title: 'Recursos Poderosos',
          subtitle: 'Tecnologia de ponta',
          tabs: [
            {
              name: 'Dashboard',
              title: 'Analytics em Tempo Real',
              description: 'Visualize métricas críticas com dashboards personalizáveis e alertas inteligentes',
              features: [
                'Gráficos interativos',
                'Filtros avançados',
                'Exportação automática',
                'Alertas customizáveis',
              ],
            },
            {
              name: 'Automação',
              title: 'Workflows Inteligentes',
              description: 'Crie automações complexas sem código com nossa interface visual',
              features: [
                'Editor drag & drop',
                'Templates prontos',
                'Integrações nativas',
                'Triggers personalizados',
              ],
            },
            {
              name: 'Colaboração',
              title: 'Time Conectado',
              description: 'Trabalhe em sincronia com chat, vídeo e documentos compartilhados',
              features: [
                'Chat em tempo real',
                'Videoconferência HD',
                'Edição colaborativa',
                'Permissões granulares',
              ],
            },
          ],
          palette: 'cyberpunk',
        },
        styles: {},
      },
      {
        id: '4',
        type: 'stats-counter',
        props: {
          title: 'Confiado Globalmente',
          subtitle: 'Números impressionantes',
          stats: [
            { number: '100', suffix: 'K+', label: 'Usuários Ativos', description: 'Em 150+ países' },
            { number: '99.99', suffix: '%', label: 'Uptime', description: 'SLA garantido' },
            { number: '5', suffix: 'M+', label: 'Tarefas', description: 'Processadas por dia' },
            { number: '24', suffix: '/7', label: 'Suporte', description: 'Time global' },
          ],
          layout: 'grid',
          palette: 'cyberpunk',
        },
        styles: {},
      },
      {
        id: '5',
        type: 'pricing',
        props: {
          title: 'Planos para Cada Necessidade',
          subtitle: 'Comece grátis, escale quando crescer',
          tiers: [
            {
              name: 'Starter',
              price: 'Grátis',
              period: 'para sempre',
              description: 'Perfeito para começar',
              features: [
                '5 projetos',
                '10GB armazenamento',
                'Integrações básicas',
                'Suporte por email',
              ],
              highlighted: false,
            },
            {
              name: 'Professional',
              price: 'R$ 99',
              period: '/mês',
              description: 'Para profissionais produtivos',
              features: [
                'Projetos ilimitados',
                '100GB armazenamento',
                'Todas integrações',
                'Suporte prioritário',
                'Analytics avançado',
                'API access',
              ],
              highlighted: true,
            },
            {
              name: 'Enterprise',
              price: 'Personalizado',
              period: '',
              description: 'Para grandes organizações',
              features: [
                'Tudo do Professional',
                'Armazenamento ilimitado',
                'SSO e SAML',
                'Suporte dedicado',
                'SLA customizado',
                'Onboarding personalizado',
              ],
              highlighted: false,
            },
          ],
        },
        styles: {},
      },
      {
        id: '6',
        type: 'cta',
        props: {
          title: 'Pronto para Transformar seu Trabalho?',
          description: 'Junte-se a milhares de equipes que já aumentaram sua produtividade em 10x',
          primaryButton: 'Começar Agora',
          secondaryButton: 'Agendar Demo',
        },
        styles: {
          backgroundColor: 'bg-gradient-to-br from-purple-900 via-blue-900 to-black',
        },
      },
    ],
  },

  {
    id: 'ai-product',
    name: 'AI Product Launch',
    category: 'produto',
    description: 'Landing page para lançamento de produto com IA',
    thumbnail: '/templates/ai-product.png',
    palette: 'neonNight',
    typography: 'modern',
    components: [
      {
        id: '1',
        type: 'hero-fullscreen',
        props: {
          title: 'IA que Entende Você',
          subtitle: 'Lançamento Oficial',
          description: 'A primeira IA verdadeiramente conversacional e contextual do mercado',
          primaryCTA: 'Testar Gratuitamente',
          secondaryCTA: 'Ver Demonstração',
          palette: 'neonNight',
          typography: 'modern',
          alignment: 'center',
          overlay: true,
          overlayOpacity: 80,
        },
        styles: {},
      },
      {
        id: '2',
        type: 'stats-counter',
        props: {
          title: 'Performance Incomparável',
          subtitle: 'Resultados reais',
          stats: [
            { number: '95', suffix: '%', label: 'Precisão', description: 'Em compreensão contextual' },
            { number: '0.3', suffix: 's', label: 'Resposta', description: 'Tempo médio' },
            { number: '50', suffix: 'x', label: 'Mais Rápido', description: 'Que soluções tradicionais' },
            { number: '1', suffix: 'M+', label: 'Interações', description: 'Processadas por hora' },
          ],
          layout: 'grid',
          palette: 'neonNight',
        },
        styles: {},
      },
      {
        id: '3',
        type: 'bento-grid',
        props: {
          items: [
            {
              title: 'Compreensão Contextual',
              description: 'Entende nuances e contexto como humano',
              icon: 'zap',
              size: 'large',
              highlight: true,
            },
            {
              title: 'Multi-idioma',
              description: 'Suporte a 95+ idiomas',
              icon: 'star',
              size: 'medium',
            },
            {
              title: 'Aprendizado Contínuo',
              description: 'Melhora com cada interação',
              icon: 'trending',
              size: 'medium',
            },
            {
              title: 'Privacidade Total',
              description: 'Seus dados nunca são compartilhados',
              icon: 'shield',
              size: 'small',
            },
            {
              title: 'Personalização',
              description: 'Se adapta ao seu estilo',
              icon: 'check',
              size: 'small',
            },
            {
              title: 'Integração Simples',
              description: 'API REST e SDKs',
              icon: 'award',
              size: 'medium',
            },
          ],
          palette: 'neonNight',
        },
        styles: {},
      },
      {
        id: '4',
        type: 'interactive-showcase',
        props: {
          title: 'Casos de Uso',
          subtitle: 'Aplicações infinitas',
          tabs: [
            {
              name: 'Atendimento',
              title: 'Suporte ao Cliente',
              description: 'Resolva dúvidas de clientes 24/7 com respostas precisas e empáticas',
              features: [
                'Respostas instantâneas',
                'Escalação inteligente',
                'Multi-canal',
                'Analytics de satisfação',
              ],
            },
            {
              name: 'Vendas',
              title: 'Assistente de Vendas',
              description: 'Qualifique leads e feche negócios com conversas naturais',
              features: [
                'Qualificação automática',
                'Agendamento inteligente',
                'CRM integration',
                'Follow-up automático',
              ],
            },
            {
              name: 'Conteúdo',
              title: 'Geração de Conteúdo',
              description: 'Crie textos, códigos e análises em segundos',
              features: [
                'Múltiplos formatos',
                'Tom personalizável',
                'SEO otimizado',
                'Revisão automática',
              ],
            },
          ],
          palette: 'neonNight',
        },
        styles: {},
      },
      {
        id: '5',
        type: 'countdown',
        props: {
          title: 'Lançamento Oficial',
          description: 'Acesso antecipado termina em:',
          endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          buttonText: 'Garantir Acesso',
          expiredText: 'Lançamento disponível!',
        },
        styles: {},
      },
      {
        id: '6',
        type: 'pricing',
        props: {
          title: 'Preços Transparentes',
          subtitle: 'Escolha o plano ideal',
          tiers: [
            {
              name: 'Developer',
              price: 'R$ 49',
              period: '/mês',
              description: 'Para desenvolvedores individuais',
              features: [
                '10.000 requisições/mês',
                'API access completo',
                'Documentação',
                'Suporte por email',
              ],
              highlighted: false,
            },
            {
              name: 'Business',
              price: 'R$ 199',
              period: '/mês',
              description: 'Para equipes e empresas',
              features: [
                '100.000 requisições/mês',
                'Tudo do Developer',
                'Webhooks',
                'Suporte prioritário',
                'Analytics avançado',
                'Custom models',
              ],
              highlighted: true,
            },
            {
              name: 'Enterprise',
              price: 'Sob consulta',
              period: '',
              description: 'Para alta escala',
              features: [
                'Requisições ilimitadas',
                'Tudo do Business',
                'Dedicated instances',
                'SLA 99.99%',
                'Suporte 24/7',
                'Custom training',
              ],
              highlighted: false,
            },
          ],
        },
        styles: {},
      },
      {
        id: '7',
        type: 'cta',
        props: {
          title: 'Experimente o Futuro da IA',
          description: 'Comece gratuitamente. Sem cartão de crédito. Cancele quando quiser.',
          primaryButton: 'Começar Agora',
          secondaryButton: 'Falar com Vendas',
        },
        styles: {
          backgroundColor: 'bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-900',
        },
      },
    ],
  },

  {
    id: 'fintech-app',
    name: 'Fintech App',
    category: 'saas',
    description: 'App financeiro com design profissional dark',
    thumbnail: '/templates/fintech.png',
    palette: 'professionalDark',
    typography: 'minimal',
    components: [
      {
        id: '1',
        type: 'hero-fullscreen',
        props: {
          title: 'O Futuro das Finanças',
          subtitle: 'Banking Reimaginado',
          description: 'Gerencie seu dinheiro com inteligência, segurança e simplicidade',
          primaryCTA: 'Abrir Conta Grátis',
          secondaryCTA: 'Conhecer Recursos',
          palette: 'professionalDark',
          typography: 'minimal',
          alignment: 'left',
          overlay: true,
          overlayOpacity: 60,
        },
        styles: {},
      },
      {
        id: '2',
        type: 'bento-grid',
        props: {
          items: [
            {
              title: 'Conta Digital Completa',
              description: 'Sem taxas, sem burocria, 100% digital',
              icon: 'check',
              size: 'large',
              highlight: true,
            },
            {
              title: 'Cartão Premium',
              description: 'Cashback em todas as compras',
              icon: 'award',
              size: 'medium',
            },
            {
              title: 'Investimentos',
              description: 'A partir de R$ 10',
              icon: 'trending',
              size: 'medium',
            },
            {
              title: 'Pix Instantâneo',
              description: 'Transferências 24/7',
              icon: 'zap',
              size: 'small',
            },
            {
              title: 'Segurança Máxima',
              description: 'Criptografia de ponta',
              icon: 'shield',
              size: 'small',
            },
            {
              title: 'Suporte Humano',
              description: 'Atendimento por pessoas reais',
              icon: 'star',
              size: 'medium',
            },
          ],
          palette: 'professionalDark',
        },
        styles: {},
      },
      {
        id: '3',
        type: 'stats-counter',
        props: {
          title: 'Confiança que Move',
          subtitle: 'Mais de 1 milhão de clientes',
          stats: [
            { number: '1.2', suffix: 'M', label: 'Clientes', description: 'Pessoas satisfeitas' },
            { number: '5', suffix: 'B+', label: 'Movimentado', description: 'Em transações seguras' },
            { number: '4.8', suffix: '/5', label: 'Avaliação', description: 'Na App Store' },
            { number: '< 1', suffix: 'min', label: 'Abertura', description: 'Tempo médio' },
          ],
          layout: 'grid',
          palette: 'professionalDark',
        },
        styles: {},
      },
      {
        id: '4',
        type: 'interactive-showcase',
        props: {
          title: 'Tudo em Um Só App',
          subtitle: 'Simplicidade que funciona',
          tabs: [
            {
              name: 'Conta',
              title: 'Conta Completa',
              description: 'Tudo que você precisa sem complicação e sem taxas escondidas',
              features: [
                'Transferências ilimitadas',
                'Pix sem limites',
                'Boletos gratuitos',
                'Saques grátis',
              ],
            },
            {
              name: 'Cartão',
              title: 'Cartão Inteligente',
              description: 'Controle total dos seus gastos com cashback automático',
              features: [
                '2% de cashback',
                'Sem anuidade',
                'Limites personalizados',
                'Bloqueio por app',
              ],
            },
            {
              name: 'Investir',
              title: 'Investimentos Simples',
              description: 'Faça seu dinheiro render com opções para todos os perfis',
              features: [
                'CDB, Tesouro, Ações',
                'Consultoria gratuita',
                'Sem taxa de corretagem',
                'Rendimento diário',
              ],
            },
          ],
          palette: 'professionalDark',
        },
        styles: {},
      },
      {
        id: '5',
        type: 'form',
        props: {
          title: 'Abra sua conta em 2 minutos',
          description: 'Sem burocracia, sem papel, 100% pelo celular',
          fields: [
            { name: 'nome', label: 'Nome Completo', type: 'text', required: true },
            { name: 'cpf', label: 'CPF', type: 'text', required: true },
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'telefone', label: 'Telefone', type: 'tel', required: true },
          ],
          buttonText: 'Abrir Minha Conta',
          successMessage: 'Conta criada! Baixe o app e comece a usar.',
        },
        styles: {},
      },
      {
        id: '6',
        type: 'cta',
        props: {
          title: 'Junte-se a 1 Milhão de Pessoas',
          description: 'Abra sua conta grátis e ganhe R$ 20 de bônus de boas-vindas',
          primaryButton: 'Abrir Conta Agora',
          secondaryButton: 'Ver Como Funciona',
        },
        styles: {
          backgroundColor: 'bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900',
        },
      },
    ],
  },

  {
    id: 'creative-agency',
    name: 'Creative Agency',
    category: 'marketing',
    description: 'Agência criativa com design vibrante',
    thumbnail: '/templates/creative.png',
    palette: 'electricPurple',
    typography: 'creative',
    components: [
      {
        id: '1',
        type: 'hero-fullscreen',
        props: {
          title: 'Criatividade sem Limites',
          subtitle: 'Award-Winning Agency',
          description: 'Transformamos marcas em experiências inesquecíveis',
          primaryCTA: 'Ver Portfolio',
          secondaryCTA: 'Começar Projeto',
          palette: 'electricPurple',
          typography: 'creative',
          alignment: 'center',
          overlay: true,
          overlayOpacity: 50,
        },
        styles: {},
      },
      {
        id: '2',
        type: 'bento-grid',
        props: {
          items: [
            {
              title: 'Branding',
              description: 'Identidade visual que marca presença',
              icon: 'star',
              size: 'large',
              highlight: true,
            },
            {
              title: 'Design Digital',
              description: 'Interfaces que encantam',
              icon: 'zap',
              size: 'medium',
            },
            {
              title: 'Marketing',
              description: 'Campanhas que convertem',
              icon: 'trending',
              size: 'medium',
            },
            {
              title: 'Motion Design',
              description: 'Animações impactantes',
              icon: 'award',
              size: 'small',
            },
            {
              title: 'Social Media',
              description: 'Conteúdo viral',
              icon: 'check',
              size: 'small',
            },
            {
              title: 'Estratégia',
              description: 'Planejamento completo',
              icon: 'shield',
              size: 'medium',
            },
          ],
          palette: 'electricPurple',
        },
        styles: {},
      },
      {
        id: '3',
        type: 'stats-counter',
        props: {
          title: 'Resultados que Falam',
          subtitle: 'Prêmios e reconhecimento',
          stats: [
            { number: '200', suffix: '+', label: 'Projetos', description: 'Entregues com sucesso' },
            { number: '50', suffix: '+', label: 'Clientes', description: 'Marcas satisfeitas' },
            { number: '15', suffix: '', label: 'Prêmios', description: 'Reconhecimento internacional' },
            { number: '10', suffix: 'x', label: 'ROI Médio', description: 'Para nossos clientes' },
          ],
          layout: 'grid',
          palette: 'electricPurple',
        },
        styles: {},
      },
      {
        id: '4',
        type: 'cta',
        props: {
          title: 'Vamos Criar Algo Incrível?',
          description: 'Agende uma conversa e descubra como podemos elevar sua marca',
          primaryButton: 'Agendar Reunião',
          secondaryButton: 'Ver Cases',
        },
        styles: {
          backgroundColor: 'bg-gradient-to-br from-purple-900 via-pink-900 to-purple-900',
        },
      },
    ],
  },
];
